### ISSUE TITLE
生成远程端时，遇错

### ISSUE THREAD

**Issue by briteming** [xxxsen/wcf#1]
hi.

root@umh:~/wcf-by-xxxsen/wcf# cd src/wcf/cmd/server
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# ls
host.rule  server.go  server.json  userinfo.dat
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# go build
../../relay/relay_acceptor.go:11:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/root/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/root/wcf-by-xxxsen/wcf/src/github.com/golang/protobuf/proto (from $GOPATH)
../../../lb/loadbalance.go:7:2: cannot find package "github.com/pkg/errors" in any of:
	/root/go/src/github.com/pkg/errors (from $GOROOT)
	/root/wcf-by-xxxsen/wcf/src/github.com/pkg/errors (from $GOPATH)
server.go:7:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/root/go/src/github.com/sirupsen/logrus (from $GOROOT)
	/root/wcf-by-xxxsen/wcf/src/github.com/sirupsen/logrus (from $GOPATH)
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# go build server.go
../../relay/relay_acceptor.go:11:2: cannot find package "github.com/golang/protobuf/proto" in any of:
	/root/go/src/github.com/golang/protobuf/proto (from $GOROOT)
	/root/wcf-by-xxxsen/wcf/src/github.com/golang/protobuf/proto (from $GOPATH)
../../../lb/loadbalance.go:7:2: cannot find package "github.com/pkg/errors" in any of:
	/root/go/src/github.com/pkg/errors (from $GOROOT)
	/root/wcf-by-xxxsen/wcf/src/github.com/pkg/errors (from $GOPATH)
server.go:7:2: cannot find package "github.com/sirupsen/logrus" in any of:
	/root/go/src/github.com/sirupsen/logrus (from $GOROOT)
	/root/wcf-by-xxxsen/wcf/src/github.com/sirupsen/logrus (from $GOPATH)
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server#

怎么解决？

**Comment by xxxsen** [comment]
@briteming 
看日志应该是缺少了依赖。。
```
cannot find package "github.com/sirupsen/logrus"
```
像这种， 可以go get -u "github.com/sirupsen/logrus" 下载依赖,

**Comment by xxxsen** [comment]
@briteming 如果实在不知道怎么整的话。。我这边更新了release文件。可以直接使用。。

**Comment by briteming** [comment]
哦，
root@umh:~/wcf-by-xxxsen/wcf#
root@umh:~/wcf-by-xxxsen/wcf# ls
bin  build.bat	pkg  src
root@umh:~/wcf-by-xxxsen/wcf# echo $GOPATH
/root/wcf-by-xxxsen/wcf
root@umh:~/wcf-by-xxxsen/wcf# go get -u -v github.com/golang/protobuf/proto
root@umh:~/wcf-by-xxxsen/wcf# go get -u -v github.com/pkg/errors
root@umh:~/wcf-by-xxxsen/wcf# go get -u -v github.com/sirupsen/logrus
root@umh:~/wcf-by-xxxsen/wcf# cd src/wcf/cmd/server/
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# go build server.go
(成功生成了可执行文件server)
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# ls
host.rule  server  server.go  server.json  userinfo.dat
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# nano server.json
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# cat server.json
{
	"localaddr":"0.0.0.0:8020",
	"timeout":2,
	"userinfo":"/root/wcf-by-xxxsen/wcf/src/wcf/cmd/server/userinfo.dat",
	"encrypt":"xor",
	"key":"iloveson",
	"host":"/root/wcf-by-xxxsen/wcf/src/wcf/cmd/server/host.rule"
}
root@umh:~/wcf-by-xxxsen/wcf/src/wcf/cmd/server# ./server -config server.json

就ok了
