### ISSUE TITLE
怎么连不上服务器了？

### ISSUE THREAD

**Issue by luckypoem** [xxxsen/wcf#2]
hi.

在mac的终端窗口里显示：
ERRO[2018-10-08 09:44:14] Dial connection to proxy/target svr fail, err:dial tcp my-vps-ip:8020: i/o timeout, svr addr:my-vps-ip:8020  id=29 local="127.0.0.1:56887" net=socks remote="api.fczbl.vip:443"

服务器端运行正常：
root@umh:~# lsof -i:8020
COMMAND   PID USER   FD   TYPE    DEVICE SIZE/OFF NODE NAME
server  21270 root    5u  IPv6 127293544      0t0  TCP *:8020 (LISTEN)
root@umh:~#

怎么回事？如何解决？

**Comment by xxxsen** [comment]
@luckypoem 看日志是连接超时了。。你2边配置的端口一致吗？ 看你日志一个是443, 一个又是8020

**Comment by luckypoem** [comment]
现在又自动恢复正常了。感觉这个wcf没有以前那个sockstunnel稳定啊。wcf使用的第二天就出故障。

**Comment by xxxsen** [comment]
@luckypoem 原理都是一样的。。我这边现在也用这个。。目前看还是很稳定的。。

**Comment by xxxsen** [comment]
你把local.json的kcp去掉，只用tcp应该会好一点。。目前看。。用kcp好像会偶尔会出现连不上的情况。。

**Comment by luckypoem** [comment]
还不错了，谢谢你开发了这么好用的fq软件

**Comment by xxxsen** [comment]
@luckypoem 哈哈。。。使用过程中。。有什么bug及时反馈哈。。
